[WIP] Create Zopim chat component
comparaonline/chat-component pull request #1
Opened 2017-05-30 22:15 UTC by izaban

2017-06-06 22:42 UTC, insxne requested changes

2017-06-06 22:42 UTC, insxne commented on .babelrc
> +        "plugins": ["transform-es2015-modules-commonjs"]
Le agregaste tests?

2017-06-06 22:42 UTC, insxne commented on .eslintrc.js
> +  'extends': 'airbnb',
Extiende desde @comparaonline/eslint-config

2017-06-06 22:42 UTC, insxne commented on README.md
> +$ npm install --save comparaonline/chat-component
👏

2017-06-06 22:42 UTC, insxne commented on package.json
> +    "react-google-tag-manager": "^2.1.0"
No estas ocupando `react-google-tag-manager` o si?

2017-06-06 22:42 UTC, insxne commented on package.json
> +    "webpack-cleanup-plugin": "^0.5.1"
¿Estas ocupando toda estas librerías?

2017-06-06 22:42 UTC, insxne commented on package.json
> +    "amplitude"
Esos no son los keywords cierto?!

2017-06-06 22:42 UTC, insxne commented on src/ZopimChat.js
> +  }
`return !this.state.isOpen && React.cloneElement(this.props.children, { onClick: this.onClick })`

2017-06-06 22:42 UTC, insxne commented on src/ZopimChat.js
> +  }
Es raro igual si `isOpen` devuelves `null`?

2017-06-06 22:51 UTC, izaban commented on .babelrc
> +      ["react"]
Sí, si borro esa línea no puedo hacer render del componente.

2017-06-06 22:57 UTC, izaban commented on package.json
> +    "react-google-tag-manager": "^2.1.0"
No, borrado.

2017-06-06 22:57 UTC, izaban commented on package.json
> +    "amplitude"
No, cambiado a: "react", "chat" y "zopim".

2017-06-06 22:58 UTC, izaban commented on src/ZopimChat.js
> +  }
Si, cierto. Cambiado a una línea.

2017-06-06 22:59 UTC, izaban commented on .babelrc
> +        "plugins": ["transform-es2015-modules-commonjs"]
No, borro el objeto "env".

2017-06-07 00:35 UTC, insxne approved these changes

2017-06-07 00:37 UTC, merged